export const itemData=[
    {
        item_img:'/assets/image/Bonda.jpg'
    },
    {
        item_img:'/assets/image/Dosa.jpg'
    },
    {
        item_img:'/assets/image/Idli.jpg'
    },
    {
        item_img:'/assets/image/Juice.jpg'
    },
    {
        item_img:'/assets/image/Pancake.jpg'
    },
    {
        item_img:'/assets/image/Paratha.jpg'
    },
    {
        item_img:'/assets/image/Poha.jpg'
    },
    {
        item_img:'/assets/image/Poori.jpg'
    },
    {
        item_img:'/assets/image/Vada.jpg'
    },
]
